### ISSUE TITLE
how to generate types.generated.go

### ISSUE THREAD

**Issue by ikaven1024** [kubeup/archon#4]
could u support a script for generate *.generated.go in this project?

**Comment by ledzep2** [comment]
The same way k8s produces its `types.generated.go`.

```bash
go get github.com/ugorji/go/codec/codecgen
codecgen -d 1234 -o types.generated.go types.go
```

And for `zz_generated.defaults.go`. You will need to build `kubernetes/cmd/libs/go2idl/defaulter-gen`.
And run in `/pkg/cluster`
```bash
defaulter-gen -i .
```

Yes. We should probably have a script to do this and maybe a guide for hackers somewhere in the repo.
